export default {
  "graphqlEndpoint": "https://t27mtzmoh5h4pjidgmf5fm32em.appsync-api.us-east-2.amazonaws.com/graphql",
  "region": "us-east-2",
  "authenticationType": "API_KEY",
  "apiKey": "da2-e6aw3f3vznbf5bdn6qu3gthcsi"
}


// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile =  {
//   "aws_appsync_graphqlEndpoint": "https://t27mtzmoh5h4pjidgmf5fm32em.appsync-api.us-east-2.amazonaws.com/graphql",
//   "aws_appsync_region": "us-east-2",
//   "aws_appsync_authenticationType": "API_KEY",
//   "aws_appsync_apiKey": "da2-e6aw3f3vznbf5bdn6qu3gthcsi",
// };

// export default awsmobile;


// export default {
//   "graphqlEndpoint": "https://o5gj47tjvfheplsohpo42e2j6q.appsync-api.us-east-1.amazonaws.com/graphql",
//   "region": "us-east-1",
//   "authenticationType": "API_KEY",
//   "apiKey": "da2-ha67aztnifbnnctrnxn3duj25m"
// }


